language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t aaron160487/simpleciapp -f Dockerfile.dev .

script:
    - docker run -e CI=true aaron160487/simpleciapp npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "simpleciapp"
   env: "simpleciapp-env-1"
   bucket_name: "elasticbeanstalk-us-east-2-781077946232"
   bucket_path: "simpleciapp"
   on:
    branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key: "$AWS_SECRET_KEY"

  