language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t aaron160487/SimpleCIApp -f Dockerfile.dev .

script:
  - docker run -e CI=true aaron160487/SimpleCIApp npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "SimpleCIAp"
   env: "SimpleCIAp-env"
   bucket_name: "elasticbeanstalk-us-east-1-781077946232"
   bucket_path: "SimpleCIApp"
   on:
    branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key: "$AWS_SECRET_KEY"

  